plantable-blocks:
  - minecraft:mud
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

aquatic-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:gravel

sugarcane-plantable-blocks:
  - minecraft:mud
  - minecraft:sand
  - minecraft:red_sand
  - minecraft:grass_block
  - minecraft:podzol
  - minecraft:dirt
  - minecraft:coarse_dirt
  - minecraft:moss_block
  - minecraft:rooted_dirt

dripleaf-plantable-blocks:
  - minecraft:mud
  - minecraft:clay
  - minecraft:coarse_dirt
  - minecraft:dirt
  - minecraft:farmland
  - minecraft:grass_block
  - minecraft:moss_block
  - minecraft:mycelium
  - minecraft:podzol
  - minecraft:rooted_dirt