name: CD

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      repo_url: ${{ github.server_url }}/${{ github.repository }}
      changelog: CHANGELOG.md
      release_changelog: RELEASE_CHANGELOG.md
      start_regex: "^## \\[Unreleased\\]"
      end_regex: "^## "

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'
  
      - name: Check for version bump
        run: sh ./.scripts/check-version-bump.sh

      - name: Create artifacts
        run: sh ./.scripts/pack.sh

      - name: Grab release changelog
        if: env.version-bumped == 'true'
        run: sh ./.scripts/grab-release-changelog.sh

      - name: Update changelog
        if: env.version-bumped == 'true'
        run: sh ./.scripts/update-changelog.sh

      - name: Push changelog
        if: env.version-bumped == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Polyhedral-Bot
          author_email: polybot@protonmail.com
          message: Version ${{ env.version }}
          tag: v${{ env.version }} -F ${{ env.release_changelog }} --cleanup=verbatim
          add: CHANGELOG.md

      - name: Release
        if: env.version-bumped == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          body_path: ${{ env.release_changelog }}
          files: |
            .artifacts/*

      - name: Release latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            .artifacts/*
